<#macro page>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Getting Started: Serving Web Content</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/style.css">
    </head>
    <body>
    <#nested>
    </body>
    </html>
</#macro>